name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: DEPLOY on AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: zip app folder
        run: zip -r ./simple-api-deployment.zip ./app

      - name: Deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 --acl private ./simple-api-deployment.zip s3://simple-api-deployment/

      - name: CodeDeploy
        run: |
          aws deploy create-deployment --region ap-northeast-2 
          --application-name simple-api-deployment --deployment-group-name dev 
          --s3-location bucket=simple-api-deployment,key=simple-api-deployment.zip,bundleType=zip
